default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_host: <%= ENV["SMTP_HOST"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user: <%= ENV["SMTP_USER"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
